.travis.yml, package.json
=> changed some text to  match our project

client/components/all-products.js, client/routes.js, client/store/all-products.js, server/api/all-products.js
=> all products vertical slice

client/components/single-product.js, client/store/single-product.js, script/seed.js, server/api/single-product.js, server/db/models/index.js, server/db/models/product.js
=> Singlepage

client/components/all-products.js, client/components/index.js, client/components/single-product.js, client/routes.js, client/store/index.js, client/store/single-product.js, server/api/all-products.js, server/api/index.js, server/api/single-product.js
---
made single Product store an object  containing  the product object, fixed the url matching for fetching single product
=> finished index files  for single/all products

client/store/all-products.spec.js, client/store/single-product.spec.js, package-lock.json, server/api/all-products.spec.js
Guzel and I worked on adding test specs for a number of additions: redux thunks, and our all products route. Please take a look, thank you.
=> addition of redux thunk tests and all products route test

server/api/single-product.spec.js
---
api test  for singleproduct
=> a test for single product

client/app.js, client/components/footer.js, client/components/index.js, client/components/navbar.js, package-lock.json, package.json, public/index.html, server/db/models/cart.js, server/db/models/index.js
=> first attempts at bootstrap

client/components/cart.js, client/components/navbar.js, client/components/single-product.js
=> added cart component

client/components/all-products.js, client/components/cart.js, client/components/single-product.js, client/store/cart.js, client/store/single-product.js, server/api/cart.js, server/api/single-product.js
=> fixes from lunch

client/components/navbar.js
=> added link to allproducts

server/api/cart.js, server/index.js
=> some moddifications

client/components/cart.js, script/seed.js, server/db/models/user.js
=> minorchanges

.travis.yml
This should update our Heroku!
=> travis active deployment

client/components/all-components.spec.js, client/components/navbar.js, client/components/user-profile.js, client/store/user.js, server/db/models/product.spec.js
=> user profile

client/components/navbar.js, client/routes.js, server/auth/index.js
=> security changes from friday

client/components/user-home.spec.js, server/api/all-products.spec.js
=> quick test

client/components/cart.js, client/store/cart.js, server/api/cart.js, server/api/order-history.js, server/db/models/index.js, server/db/models/order.js
=> databasechanges

server/api/all-products.js, server/api/cart.js, server/api/order-history.js, server/api/single-product.js
=> Api protect

server/api/order-history.js
=> Minor api fix

client/components/Main.js, client/components/single-product.js
=> alert for add to cart

client/components/all-components.spec.js
=> updated test

client/components/auth-form.js, public/style.css, server/auth/google.js
=> redirect fix

client/components/auth-form.js
=> oauth fix?

client/components/auth-form.js
=> trying to fix oauth
